' Michael Voell
' Approved Travel Requests
' 2/18/2016
' Purpose: To look through a database and see approved travel requets from employees.

Option Strict On

Public Class frmApprovedTravel

    Private Sub ApprovedTravelRequestsBindingNavigatorSaveItem_Click(sender As System.Object, e As System.EventArgs) Handles ApprovedTravelRequestsBindingNavigatorSaveItem.Click
        ' This click event is generated by the database wizard

        Me.Validate()
        Me.ApprovedTravelRequestsBindingSource.EndEdit()
        Me.TableAdapterManager.UpdateAll(Me.TravelDataSet)

    End Sub

    Private Sub frmApprovedTravel_Load(sender As System.Object, e As System.EventArgs) Handles MyBase.Load
        ' The database creates this method
        ' The Try/Catch block catches an exception caused by a missing database file

        Try
            'TODO: This line of code loads data into the 'TravelDataSet.ApprovedTravelRequests' table. You can move, or remove it, as needed.
            Me.ApprovedTravelRequestsTableAdapter.Fill(Me.TravelDataSet.ApprovedTravelRequests)
        Catch ex As Exception
            MsgBox("Could not connect to Database. Please try again.", , "Database Error")
            Close()
        End Try

    End Sub
End Class
